- name: Playbook1
  hosts: localhost
  # vars:
  #   URL: Global.cloudblitz.in

  # vars_files: url.yml

  #vars_prompt:
  #- name: URL
  #     prompt: "Enter URL"
  #     private: no
  #     # private for URL hidden

  tasks:
    - shell: hostname >> hostname.txt
    - name: Print messages_1
      debug:
        msg: "{{URL}}"
      # vars:
      #   URL: Local_url